version: "2"
services:
    nginx:
      image: nginx:latest
      ports:
        - "8000:8000"
      volumes:
        - .:/code
        - ./config/nginx:/etc/nginx/conf.d
        - /static:/static
      depends_on: 
        - web
    web:
      build: .
      command: bash -c "sleep 4 && python ./manage.py makemigrations && python ./manage.py migrate && gunicorn hccworkshop.wsgi -b 0.0.0.0:8000"
      volumes:
        - .:/code
        - /static:/static
      expose:
        - "8000"
      depends_on:
        - "db"
        - "redis"
    db:
      image: postgres
    redis:
      image: redis