version: "2"
services:
    nginx:
      image: nginx:latest
      ports:
        - "1234:8000"
      volumes:
        - .:/code
        - ./config/nginx:/etc/nginx/conf.d
        - /static:/static
      depends_on: 
        - web
    web:
      build: .
      command: bash -c "sleep 4 && python ./manage.py makemigrations && python ./manage.py migrate && gunicorn hccworkshop.wsgi -b 0.0.0.0:8000"
      volumes:
        - .:/code
        - /static:/static
      expose:
        - "8000"
      depends_on:
        - "db"
        - "redis"
        - "rabbit"
    db:
      image: postgres
    redis:
      image: redis
    rabbit:
      image: rabbitmq
      environment:
        - RABBITMQ_DEFAULT_USER=admin
        - RABBITMQ_DEFAULT_PASS=admin
      ports:
        - "5672:5672"
        - "15672:15672"
    worker:
      build: .
      command: bash -c "sleep 10 && celery -A hccworkshop worker -l info"
      volumes:
        - .:/code
      links:
        - "db"
        - "redis"
        - "rabbit"
      depends_on:
        - "rabbit"