version: "2"
services:
    web:
      build: .
      command: bash -c "sleep 4 && python ./manage.py makemigrations && python ./manage.py migrate && python manage.py runserver 0.0.0.0:8000"
      volumes:
        - .:/code
        - /static:/static
      ports: 
        - "8000:8000"
      depends_on:
        - "db"
        - "redis"
      environment:
        - DEBUG=True
    db:
      image: postgres
    redis:
      image: redis
    rabbit:
      image: rabbitmq
      environment:
        - RABBITMQ_DEFAULT_USER=admin
        - RABBITMQ_DEFAULT_PASS=admin
      ports:
        - "5672:5672"
        - "15672:15672"
    worker:
      build: .
      command: bash -c "sleep 10 && celery -A hccworkshop worker -l info"
      volumes:
        - .:/code
      links:
        - "db"
        - "redis"
        - "rabbit"
      depends_on:
        - "rabbit"
