version: "2"
services:
    web:
      build: .
      command: bash -c "sleep 4 && python ./manage.py makemigrations && python ./manage.py migrate && python ./manage.py runserver 0.0.0.0:80"
      volumes:
        - .:/code
      ports:
        - "80:80"
      depends_on:
        - "db"
        - "redis"
    db:
      image: postgres
    redis:
      image: redis
