# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-15 22:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0002_mappings_correct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mappings',
            name='answer',
            field=models.CharField(choices=[('gmaps', 'Google Maps'), ('spatial', 'Using Spatial Reasoning'), ('notspatial', 'Not Using Spatial Reasoning'), ('compass', 'A compass')], max_length=100),
        ),
    ]
