# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 12:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('design', '0003_auto_20160916_0851'),
    ]

    operations = [
        migrations.CreateModel(
            name='Constraints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Time Collected')),
                ('answer', models.CharField(choices=[('stopuse', 'To stop a user from using an interface.'), ('coins', 'To teach people what Australian $2 coins look like.'), ('simplify', 'To help simplify use of an interface.')], max_length=100)),
                ('correct', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='skilllevel',
            name='user',
        ),
        migrations.DeleteModel(
            name='SkillLevel',
        ),
    ]
