# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-03 10:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0004_auto_20160920_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constraints',
            name='answer',
            field=models.CharField(choices=[('stopuse', 'To stop a user from using an interface.'), ('coins', 'To teach people what Australian $2 coins look like.'), ('simplify', 'To help simplify the use of an interface.')], max_length=100),
        ),
        migrations.AlterField(
            model_name='mappings',
            name='answer',
            field=models.CharField(choices=[('gmaps', 'Google Maps'), ('spatial', 'Using Spatial Reasoning'), ('notspatial', 'Not Using Spatial Reasoning'), ('compass', 'A Compass')], max_length=100),
        ),
    ]
