# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-06 05:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Time Collected')),
                ('gazedata', models.TextField()),
                ('age', models.TextField()),
                ('education', models.TextField()),
                ('gender', models.TextField()),
                ('major', models.TextField()),
                ('language', models.TextField()),
                ('vision', models.TextField()),
            ],
        ),
    ]
