# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-06 10:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionnaire',
            name='gazedata',
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='education',
            field=models.CharField(choices=[('highschool', 'High School'), ('tafe', 'Diploma \\ Grad. cert.'), ('undergrad', 'Undergradute Degree'), ('master', 'Masters Degree'), ('phd', 'PhD'), ('other', 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='gender',
            field=models.CharField(choices=[('female', 'Female'), ('male', 'Male'), ('other', 'I would prefer not to say')], max_length=100),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='language',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='major',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='vision',
            field=models.CharField(choices=[('normal', 'Yes'), ('abnormal', 'No')], max_length=100),
        ),
    ]
