# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-07 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0003_experimentpage_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='image_ref',
            field=models.CharField(default=3, max_length=200),
            preserve_default=False,
        ),
    ]
