# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-09 05:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0006_auto_20160909_0526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sequences',
            name='sequence',
            field=models.CharField(choices=[('1', 'H,R - 1,2,6,3,5,4'), ('2', 'H,R - 2,3,1,4,6,5'), ('3', 'H,R - 3,4,2,5,1,6'), ('4', 'H,R - 4,5,3,6,2,1'), ('5', 'H,R - 5,6,4,1,3,2'), ('6', 'H,R - 6,1,5,2,4,3'), ('7', 'R,S - 1,2,6,3,5,4'), ('8', 'R,S - 2,3,1,4,6,5'), ('9', 'R,S - 3,4,2,5,1,6'), ('10', 'R,S - 4,5,3,6,2,1'), ('11', 'R,S - 5,6,4,1,3,2'), ('12', 'R,S - 6,1,5,2,4,3'), ('13', 'S,H - 1,2,6,3,5,4'), ('14', 'S,H - 2,3,1,4,6,5'), ('15', 'S,H - 3,4,2,5,1,6'), ('16', 'S,H - 4,5,3,6,2,1'), ('17', 'S,H - 5,6,4,1,3,2'), ('18', 'S,H - 6,1,5,2,4,3')], max_length=100, unique=True),
        ),
    ]
