# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-11 01:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0007_auto_20160909_0530'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experimentpage',
            old_name='question',
            new_name='question_number',
        ),
        migrations.AddField(
            model_name='experimentpage',
            name='image_ref',
            field=models.CharField(default='kjashdf', max_length=200),
            preserve_default=False,
        ),
    ]
