# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-12 03:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0008_auto_20160911_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experimentpage',
            name='answer',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='experimentpage',
            name='gazedata',
            field=models.TextField(null=True),
        ),
    ]
