# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-12 03:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0009_auto_20160912_0327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experimentpage',
            name='answer',
            field=models.CharField(blank=True, default='hello', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='experimentpage',
            name='gazedata',
            field=models.TextField(blank=True, default='test'),
            preserve_default=False,
        ),
    ]
