# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-12 06:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reading_tracking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingeyegaze',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
