# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-16 04:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reading_tracking', '0002_readingeyegaze_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingeyegaze',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 8, 16, 4, 3, 39, 197185, tzinfo=utc), verbose_name='Time Collected'),
            preserve_default=False,
        ),
    ]
