# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-13 00:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eyetracking', '0003_imagegaze'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dotsgaze',
            name='gazedata',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='imagegaze',
            name='image1',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='imagegaze',
            name='image2',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='imagegaze',
            name='image3',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='readinggaze',
            name='gazedata',
            field=models.TextField(blank=True),
        ),
    ]
