# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-13 04:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eyetracking', '0004_auto_20160913_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dotsgaze',
            name='gazedata',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='imagegaze',
            name='image1',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='imagegaze',
            name='image2',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='imagegaze',
            name='image3',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='readinggaze',
            name='gazedata',
            field=models.TextField(),
        ),
    ]
