# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-11 09:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newslettersignup',
            name='signup_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 8, 11, 9, 34, 34, 529033, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
