# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-11 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_newslettersignup_signup_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newslettersignup',
            name='signup_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date Signed Up'),
        ),
    ]
