# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-15 22:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_workshopuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshopuser',
            name='level',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
