# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-15 22:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20160916_0818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshopuser',
            name='level',
            field=models.CharField(choices=[('0', 'Baby'), ('1', 'Student'), ('2', 'Doctor'), ('3', 'Scientist'), ('4', 'Mac Scientist'), ('5', 'Wizard')], default=0, max_length=100),
        ),
    ]
