# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-15 23:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20160916_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshopuser',
            name='level',
            field=models.CharField(choices=[('0', 'Baby'), ('1', 'Student'), ('2', 'Teacher'), ('3', 'Doctor'), ('4', 'Professor'), ('5', 'Mad Scientist'), ('6', 'Superhero'), ('7', 'Alien'), ('8', 'Wizard'), ('9', 'A.I.')], default=0, max_length=100),
        ),
    ]
