# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-09 08:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20160930_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshopuser',
            name='level',
            field=models.CharField(choices=[('0', '0 - Baby'), ('1', '1 - Student'), ('2', '2 - Master'), ('3', '3 - Teacher'), ('4', '4 - Researcher'), ('5', '5 - Doctor'), ('6', '6 - Professor'), ('7', '7 - Astronaut'), ('8', '8 - Mad Scientist'), ('9', '9 - Superhero'), ('10', '10 - Alien'), ('11', '11 - Wizard'), ('12', '12 - A.I.')], default='0', max_length=100),
        ),
    ]
