# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-25 07:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0013_workshopuser_ethics_approval'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='completedactivity',
            options={'ordering': ('activity',), 'verbose_name': 'completed activity', 'verbose_name_plural': 'completed activity'},
        ),
        migrations.AlterModelOptions(
            name='workshopuser',
            options={'verbose_name': 'workshop details', 'verbose_name_plural': 'workshop details'},
        ),
        migrations.RemoveField(
            model_name='completedactivity',
            name='user',
        ),
        migrations.AddField(
            model_name='completedactivity',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
