# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-03 03:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_workshopuser_ethics_approval'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='completedactivity',
            options={'ordering': ('activity',), 'verbose_name': 'completed activity', 'verbose_name_plural': 'completed activity'},
        ),
        migrations.AlterModelOptions(
            name='workshopuser',
            options={'verbose_name': 'workshop details', 'verbose_name_plural': 'workshop details'},
        ),
    ]
