# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-25 07:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20161225_1824'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='completedactivity',
            options={},
        ),
    ]
