# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-04 06:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20170103_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='newslettersignup',
            name='area_of_interest',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newslettersignup',
            name='first_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='newslettersignup',
            name='last_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='newslettersignup',
            name='school',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='newslettersignup',
            name='year',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
