# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-08 20:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20170104_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshopuser',
            name='level',
            field=models.CharField(choices=[('0', '0 - Baby'), ('1', '1 - Pre-schooler'), ('2', '2 - Primary-schooler'), ('3', '3 - Teenager'), ('4', '4 - Undergraduate'), ('5', '5 - Master'), ('6', '6 - Teacher'), ('7', '7 - Doctor'), ('8', '8 - Researcher'), ('9', '9 - Professor'), ('10', '10 - Astronaut'), ('11', '11 - Mad Scientist'), ('12', '12 - Superhero'), ('13', '13 - Advanced Alien'), ('14', '14 - Wizard'), ('15', '15 - Supercomputer'), ('16', '16 - Skynet'), ('17', '17 - Unicorn')], default='0', max_length=100),
        ),
    ]
