# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-25 07:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0015_auto_20161225_1834'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='completedactivity',
            options={'ordering': ('activity',), 'verbose_name': 'completed activity', 'verbose_name_plural': 'completed activity'},
        ),
        migrations.RemoveField(
            model_name='completedactivity',
            name='user',
        ),
        migrations.AddField(
            model_name='completedactivity',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
